// components/TextUnwrapper.vue
<template>
  <div class="text-unwrapper">
    <section class="text-unwrapper-loadfile">
      <text-reader @load="loadfile($event)">
        <fa icon="file-upload"/>Upload File
      </text-reader>
    </section>

    <section class="text-unwrapper-textarea-section">
      <textarea
        v-model="text"
        placeholder="Paste text to unwrap here"
        class="text-unwrapper-textarea"
        :style="textAreaWidth"
      ></textarea>
    </section>

    <section class="text-unwrapper-controls">
      <button type="button" @click="unwrap">
        <fa icon="align-left"/>Unwrap
      </button>
      <button type="button" @click="download">
        <fa icon="download"/>Download
      </button>
      <button
        type="button"
        v-clipboard:copy="text"
        v-clipboard:success="copySuccess"
        v-clipboard:error="copyError"
      >
        <fa icon="copy"/>Copy Text
      </button>
    </section>

    <section class="text-unwrapper-settings-section">
      <text-unwrapper-settings v-model.number="linewidth"/>
    </section>
  </div>
</template>

<script>
import { saveAs } from 'file-saver'

import TextReader from '@/components/TextReader.vue'
import TextUnwrapperSettings from '@/components/TextUnwrapperSettings.vue'

export default {
  name: 'TextUnwrapper',

  components: {
    TextReader,
    TextUnwrapperSettings
  },

  data() {
    return {
      text: '',
      linewidth: this.wrapwidth
    }
  },

  props: {
    wrapwidth: {
      type: Number,
      default: 70
    }
  },

  computed: {
    textAreaWidth: function() {
      return `max-width: ${this.linewidth + 10}ch;`
    }
  },

  methods: {
    copySuccess: function(e) {
      // alert('You just copied: ' + e.text)
    },

    copyError: function(e) {
      // alert('Failed to copy text')
    },

    download: function() {
      let blob = new Blob([this.text], { type: 'text/plain;charset=utf-8' })
      saveAs(blob, 'unwrapped.txt')
    },

    loadfile: function(e) {
      this.text = e
      this.unwrap()
      this.download()
    },

    unwrap: function() {
      if (this.text == '') {
        return
      }

      let lines = this.text.split('\n')

      let unwrapped = ''
      let nextLine = ''
      let nextLineFirstWord = ''
      let extendedLine = ''

      for (let i = 0; i < lines.length; i++) {
        // Is there a next line?
        if (i + 1 < lines.length) {
          nextLine = lines[i + 1]
        } else {
          nextLine = ''
        }

        nextLineFirstWord = nextLine.split(' ', 1)[0]

        // If it exists, add the first word of the next line to this line
        if (nextLineFirstWord != ' ') {
          extendedLine = lines[i] + ' ' + nextLineFirstWord
        } else {
          extendedLine = lines[i]
        }

        if (
          lines[i].length <= this.linewidth &&
          extendedLine.length > this.linewidth
        ) {
          // then the line was wrapped so lets unwrap it
          unwrapped += lines[i] + ' '
        } else {
          unwrapped += lines[i] + '\n'
        }
      }

      this.text = unwrapped
    }
  }
}
</script>

// src/components/TextUnwrapper.tsx
import { useState, useEffect } from "react";
import { unwrap } from "@/lib";
import { saveAs } from "file-saver";

import Button from "@/components/Button";
import FileUpload from "@/components/FileUpload";
import Settings from "@/components/Settings";
import "./TextUnwrapper.css";

function TextUnwrapper() {
  const [text, setText] = useState("");
  const [wrapWidth, setWrapWidth] = useState(70);

  useEffect(
    () =>
      document.documentElement.style.setProperty(
        "--textarea-width",
        `${wrapWidth}ch`
      ),
    [wrapWidth]
  );

  function handleUnwrap() {
    setText(unwrap(text, wrapWidth));
    // console.log("Unwrapped");
  }

  function handleDownload() {
    download(text);
    // console.log("File downloaded");
  }

  function download(textToSave: string) {
    let blob = new Blob([textToSave], { type: "text/plain;charset=utf-8" });
    saveAs(blob, "unwrapped.txt");
  }

  async function handleCopy() {
    // console.log("Copying...");

    try {
      await navigator.clipboard.writeText(text);
      // console.log("Copied");
    } catch (err) {
      console.error("Copy failed! Error:", err);
    }
  }

  function handleUpload(e: React.ChangeEvent<HTMLInputElement>) {
    if (!e.target.files) return;

    const file = e.target.files[0];
    const reader = new FileReader();

    console.log("File uploading");
    reader.addEventListener("load", handleFileRead, { once: true });
    reader.readAsText(file);
  }

  function handleFileRead(e: ProgressEvent<FileReader>) {
    console.log("File uploaded");
    if (e.target?.result) {
      const newText = e.target.result as string;
      const unwrapped = unwrap(newText, wrapWidth);

      setText(unwrapped);
      download(unwrapped);
    }
  }

  return (
    <main className="text-unwrapper">
      <div className="text-unwrapper-loadfile">
        <FileUpload
          text="Upload File"
          icon="file-upload"
          onUpload={handleUpload}
        ></FileUpload>
      </div>

      <textarea
        className="text-unwrapper-textarea"
        value={text}
        onChange={(e) => setText(e.target.value)}
        placeholder="Paste text to unwrap here"
      ></textarea>

      <div className="text-unwrapper-controls">
        <Button text="Unwrap" icon="align-left" onClick={handleUnwrap}></Button>
        <Button
          text="Download"
          icon="file-download"
          onClick={handleDownload}
        ></Button>
        <Button text="Copy Text" icon="copy" onClick={handleCopy}></Button>
      </div>

      <div className="text-unwrapper-settings-section">
        <Settings wrapWidth={wrapWidth} setWrapWidth={setWrapWidth}></Settings>
      </div>
    </main>
  );
}

export default TextUnwrapper;
